# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode8
language: objective-c

env:
- DESTINATION='platform=OS X'
- DESTINATION='platform=iOS Simulator,name=iPhone 6s'
- DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

script:
- set -o pipefail && xcodebuild -workspace Weakify.xcworkspace -scheme Weakify -destination "$DESTINATION" test analyze | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
