# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode9
language: objective-c

env:
- DESTINATION="platform=OS X"
- DESTINATION="platform=iOS Simulator,name=iPhone SE"
- DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
- DESTINATION=""

script:
- if [[ $DESTINATION = "" ]]; then swift test; else set -o pipefail && xcodebuild -scheme Weakify -destination "$DESTINATION" test analyze | xcpretty -c; fi
- pod lib lint --quick --skip-tests

after_success:
- bash <(curl -s https://codecov.io/bash)
