# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode7.3
language: objective-c

script:
- set -o pipefail && xcodebuild analyze test -workspace Weakify.xcworkspace -scheme Weakify-OSX -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild analyze -workspace Weakify.xcworkspace -scheme Weakify-watchOS -sdk watchsimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild analyze test -workspace Weakify.xcworkspace -scheme Weakify-tvOS -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild analyze test -workspace Weakify.xcworkspace -scheme Weakify-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
